FROM ubuntu:bionic as builder
RUN apt update && apt upgrade -y && \
    apt install -y build-essential cmake

WORKDIR /faas
COPY . .
ENV CXXFLAGS=-DDCHECK_ALWAYS_ON
RUN ./build_deps.sh && make -j $(nproc) release

FROM ubuntu:bionic as release
WORKDIR /faas/bin
COPY --from=builder /faas/bin/release/watchdog /faas/bin/watchdog
