#!/bin/bash

PYTHON_EXEC=/usr/local/bin/python
PYTHON_ENTRY=$1
FUNC_ID=$2
WORKING_DIR=$(dirname $1)

if [ -f "$WORKING_DIR/requirements.txt" ]; then
    pip install -r $WORKING_DIR/requirements.txt
fi

DEFAULT_FUNC_WORKER_OUTPUT_DIR="/tmp/faas/func_output_${FUNC_ID}"

PYTHONPATH=/faas/python:$PYTHONPATH /faas/bin/watchdog \
    --gateway_ipc_path=${GATEWAY_IPC_PATH:-"/tmp/faas/gateway.sock"} \
    --shared_mem_path=${SHARED_MEM_PATH:-"/tmp/faas/shm"} \
    --func_config_file=${FUNC_CONFIG_FILE:-"/faas/share/func_config.json"} \
    --func_id=${FUNC_ID} --run_mode=4 \
    --fprocess="$PYTHON_EXEC $PYTHON_ENTRY" \
    --fprocess_working_dir=$WORKING_DIR \
    --max_num_func_workers=${NUM_FUNC_WORKERS:-"1"} \
    --func_worker_output_dir=${FUNC_WORKER_OUTPUT_DIR:-$DEFAULT_FUNC_WORKER_OUTPUT_DIR}
